In [21]:
import torch.nn as nn

lin = nn.Linear(3, 2)
print(lin)
print(lin.weight)
print(lin.bias)
w = lin.weight
b = lin.bias

print(w.size(0), b.size(0))

print('------')

lin2 = nn.Linear(3, 5)
print(lin2)
print(lin2.weight)
print(lin2.bias)

print('\n\n ===')
lin2.weight.data[:w.size(0), :w.size(1)] = w.data
lin2.bias.data[:b.size(0)] = b.data
print(lin2.weight)
print(lin2.bias)

Linear(in_features=3, out_features=2, bias=True)
Parameter containing:
tensor([[-0.4629, -0.3757, -0.3351],
        [ 0.1532,  0.4842, -0.5683]], requires_grad=True)
Parameter containing:
tensor([ 0.1482, -0.2935], requires_grad=True)
2 2
------
Linear(in_features=3, out_features=5, bias=True)
Parameter containing:
tensor([[-0.0507, -0.4640, -0.3700],
        [-0.1795, -0.0597, -0.2883],
        [ 0.1287,  0.1901, -0.4380],
        [ 0.0816, -0.1549,  0.1762],
        [-0.3454,  0.2525,  0.0926]], requires_grad=True)
Parameter containing:
tensor([-0.5440, -0.1612, -0.0018,  0.3072,  0.2208], requires_grad=True)


 ===
Parameter containing:
tensor([[-0.4629, -0.3757, -0.3351],
        [ 0.1532,  0.4842, -0.5683],
        [ 0.1287,  0.1901, -0.4380],
        [ 0.0816, -0.1549,  0.1762],
        [-0.3454,  0.2525,  0.0926]], requires_grad=True)
Parameter containing:
tensor([ 0.1482, -0.2935, -0.0018,  0.3072,  0.2208], requires_grad=True)


In [23]:
with open('data.txt', 'r') as fr:
    with open('data.tsv', 'w') as fw:
        for line in fr.readlines():
            print(line.strip().replace(' ', '\t', 1), file=fw)

In [24]:
with open('data.tsv', 'r') as fr:
    for line in fr.readlines():
        intent, prompt = line.strip().split('\t')
        print(intent, prompt)

POZDRAV Ahoj
POZDRAV Dobrý den
POZDRAV Čau
POZDRAV Nazdar
POZDRAV Pozdrav pánbůh
POZDRAV Zdar
POZDRAV Dobré ráno
POZDRAV Dobrý večer
POZDRAV Dobrej
POZDRAV Zdravíčko
POKYN Rozsviť LED
POKYN Zamávej
POKYN Otoč se
POKYN Zapískej
POKYN Zvedni levou ruku
POKYN Zvedni pravou ruku
POKYN Zablikej
POKYN Jdi vpřed
POKYN Rozjeď se
POKYN Zatoč
KALENDÁŘ Kolik je hodin
KALENDÁŘ Co mám v plánu zítra odpoledne
KALENDÁŘ Naplánuj schůzku na pátek ve 3
KALENDÁŘ Kolikátého je dnes
KALENDÁŘ Jaký je datum
KALENDÁŘ Co je za měsíc
KALENDÁŘ Jaký je rok
KALENDÁŘ Co je dnes za den
KALENDÁŘ Kdo má dnes svátek
KALENDÁŘ Kdo má dnes narozeniny
VYGOOGLI Kolik je států v Africe
VYGOOGLI Najdi mi restauraci v Brně
VYGOOGLI Jaký je počet obyvatel v Plzni
VYGOOGLI Kde koupit bitcoin za CZK a jaký je aktuální kurz
VYGOOGLI Kdo je prezident ve Francii
VYGOOGLI Kde budou další olympijské hry
VYGOOGLI Jak vybrat běžky
VYGOOGLI Jak napsat životopis
VYGOOGLI Jak rychle zhubnout
VYGOOGLI Jak vydělat peníze
POZNEJ Co to je?
POZ

In [20]:
import numpy as np

a = np.array([[2, 3]], ndmin=2)
c = np.array([[1, 2],[5, 4]], ndmin=2)
b = np.concatenate((a, c), axis=0)
print(a, c)
print(a.shape, c.shape)
print(b)
print(b.shape)



[[2 3]] [[1 2]
 [5 4]]
(1, 2) (2, 2)
[[2 3]
 [1 2]
 [5 4]]
(3, 2)
